version: 0.0
os: linux

files:
  - source: /miniproject4-next
    destination: /home/ubuntu/apps/miniproject4-next
    overwrite: true

  - source: /scripts
    destination: /home/ubuntu/apps/scripts
    overwrite: true

permissions:
  - object: /home/ubuntu/apps/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
