version: 0.2

env:
  variables:
    APP_DIR: "miniproject4-next"

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    commands:
      - cd $APP_DIR
      - npm ci
      - npm run build
      - cd ..

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - miniproject4-next/.next/**/*
    - miniproject4-next/package.json
    - miniproject4-next/package-lock.json
