version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version

  build:
    commands:
      - cd miniproject4-spring/miniproject04
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - chmod +x deploy.sh

artifacts:
  base-directory: miniproject4-spring/miniproject04
  files:
    - appspec.yml
    - deploy.sh
    - build/libs/*.jar